### ISSUE TITLE
How about changing the initial term for each node to 0?

### ISSUE THREAD

**Issue by LongerZrLong** [ongardie/raftscope#23]
Nice interactive explanation of raft! Thanks a lot for making it!

I am wondering is it worthwhile to change the initial term for each node to 0. Currently, the initial term for each node is 1. Thus, when the first leader comes up, its term number is 2, which seems a little different from the raft paper.

**Comment by ongardie** [comment]
Thanks @LongerZrLong. The Raft cheatsheet does describe the term as initialized at 0, but honestly it's been too long since I've looked at this code and don't remember if anything else would break in the code. I think I also saved a pre-recorded history to use for talks and that may also need to be adjusted accordingly. So, even though it might be a one-line change, it's probably not worth it to make this change unless I/someone was already in this codebase making bigger changes.

**Comment by LongerZrLong** [comment]
Thanks for your reply, @ongardie
